root = "."
tmp_dir = "/tmp"

[build]
# Binary file yields from `go build`.
bin = "/tmp/main"
# Command to build the app
cmd = "go build -o /tmp/main ."
# Watch these directories for changes
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these directories
exclude_dir = ["assets", "tmp", "vendor", ".git"]
# Ignore these files
exclude_file = []
# Watch these files for changes
include_dir = []
# Delay after each reload
delay = 1000
# Kill process before starting a new one
kill_delay = "0s"
# Send Interrupt signal before killing process
send_interrupt = false
# Poll files for changes instead of using fsnotify.
poll = true
# Poll interval (defaults to the minimum interval of 500ms).
poll_interval = 500 # ms

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
time = false

[misc]
clean_on_exit = true
