FROM debian:bookworm-slim AS chroot

# Install dependencies that will be available in the jailed environment
RUN apt-get update && apt-get install -y gcc g++ make python3 python3-pip

# Create a user and group inside the jail
RUN groupadd -g 1337 jail && useradd -u 1337 -g jail jail

FROM golang:1.24-bookworm AS base

COPY --from=chroot / /chroot

FROM ghcr.io/google/nsjail/nsjail:latest AS nsjail-stage

FROM base AS development

COPY --from=nsjail-stage /bin/nsjail /usr/bin/nsjail

RUN apt-get -y update && apt-get install -y \
    libc6 \
    libstdc++6 \
    libprotobuf32 \
    libnl-route-3-200

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN mkdir -p /compiled

RUN go mod download

CMD ["air"]